

// LOCALHOST ### 
GET http://localhost:8080/contacts

// LOCALHOST 
### 
GET http://localhost:8080/professional

###
GET http://localhost:8080/contacts/6325d9779a0a46103327dae1

###
GET http://localhost:8080/contacts/6325d9779a0a46103327dae1

###
GET http://localhost:8080/contacts/6325d9779a0a46103327dae1



// PRODUCTION Deploy ###

###
GET https://cse342-lesson2.onrender.com/professional

###
GET https://cse342-lesson2.onrender.com/contacts

###
GET https://cse342-lesson2.onrender.com/contacts/6325d9779a0a46103327dae1

